web/django_practice/articles/urls.py
from django.urls import path
from . import views

# 무슨 앱을 위한 urls인지 namespace 설정해두기
app_name = "articles"

urlpatterns = [
    path('',views.index, name="index"),
    # CRUD
    path('create/', views.create, name="create"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/update/', views.update, name="update"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    # 1:N
    path('<int:article_pk>/comments/', views.create_comments, name='create_comments'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.delete_comments, name="delete_comments"),
    # N:N
    path('<int:article_pk>/likes/', views.likes, name='likes'),

]

web/django_practice/articles/models.py
from django.db import models
from django.conf import settings
# Create your models here.

# 파이썬 기본 변수명 컨벤션 또한 장고에서도 지켜야한다. 
# 컨벤션은 오류와 관련이 있는 것이 아니다.
'''
    DB 동작과  python object 동작 구분짓기.
    django 안에서 작성하는 모든 코드는 파이썬 코드입니다.
    파이썬 객체 다루는 방법을 따른다.
'''


# 작성자 정보를 담기 위한 1:N 관계
# User Model - accounts.User 문자열 직접 작성해도 문제는 없다.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    # Article 클래스에는 user나 like users 속성이 직접 정의가 되었으나,
    # 역참조 대상에는 정의된 적이 없기 때문에, 역참조로서만 조회할 수 있다.
    # 역참조 매니저의 자동 설정 규칙은 '모델 소문자명_set' 이다.
    # Article 입장에서는 article.like_users.all 으로 조회할 수 있으나
    # User 입장에서는 user.article.set.all 으로 조회할 수 있다.
    # 이 경우 중복된 역참조 문제나, 문장 구성이 어색해질 수 있다.
    # 이러한 역참조 매서드를 쉽게 재정의 하기 위해서 related_name를 사용한다.
    title = models.CharField(max_length=100)
    content = models.TextField()
    is_hidden = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.pk}번째 게시글 {self.title}'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

web/django_practice/articles/forms.py
from django import forms
from .models import Article, Comment
'''
    Form : 모델에 대한 정보가 없는 Form을 위한 클래스

    ModelForm : 모델에 대한 정보가 있는 Form을 위한 클래스
'''
class ArticleForm(forms.ModelForm):
    '''
        HTML에서 쓸 form 태그를 구성해주는 class인데,
        field에 대한 정보가 없으면 input tag에 뭘 써야할지 알 수 없다.
        그래서, 그 field를 직접 짜준다. 정의하는 방법은 django model 정의하는 것과 똑같다.
    '''

    title = forms.CharField(
        # form 내부에서 보여줄 input을 어떻게 정의할 것인가?
        # 어떤 input으로 만들어 주는지는 누가 가지고 있는가?
        # html 태그는 여러개의 속성을 가지고 있는데, 이 속성을 쓰는 방법은 "속성명=값"방식이다.
        widget = forms.TextInput(
            attrs = {
                'class' : 'form-control',
                'placeholder' : '제목을 입력하세요.',
            }
        )
    )
    content = forms.CharField(
        widget = forms.Textarea(
            attrs= {
                'class' : 'form-control',
                'placeholder' : '내용을 입력하세요.',
            }
        )
    )
    class Meta:
        model = Article
        fields = '__all__'
        exclude = ('user','like_users')
        '''
            내가 가진 필드들 중 어떤 이름을 가진 필드들의 속성만 간단하게 수정하고 싶어.
            필드 각 이름은 고유값이니까, 
        '''
        widgets = {
            'is_hidden' : forms.RadioSelect(
                attrs={
                    'class' : 'form-check',
                },
                choices=((True, '공개'), (False, '비공개')
                         
                ),
            )


        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

web/django_practice/articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm, CommentForm
from .models import Article, Comment

# Create your views here.

def index(request):
    # articles = Article.objects.order_by('-pk')
    is_hidden = request.GET.get('is_hidden')
    if is_hidden == None or is_hidden == "True" :
        articles = Article.objects.order_by('pk')
    else : 
        articles = Article.objects.filter(is_hidden = False)

    context= {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):

    '''
        1. 생성 하기 위한 데이터를 입력할 수 있는 페이지
        2. 입력한 데이터를 토대로 실제로 데이터를 생성하는 함수    
    '''
    if request.method == 'POST' :
        form = ArticleForm(request.POST)
        # 상속 받은 Model Form 에 정의되어 있다.
        # 유효성 메서드 통과 : DB에 저장할 수 있을 것 같음
        # 항상 모든 필드에 대한 정보를 받는건 아니고
        # 사용자가 보내온 데이터가 정의된 field에 삽입하기 적절하면 저장한다.
        if form.is_valid():
            article = form.save(commit = False)
            article.user = request.user
            article.save()
            return redirect('articles:index')

    else :
        # GET 요청이 들어온 경우, Article 생성할 수 있도록 하기
        form = ArticleForm()
    context = {
        'form' : form,
    }
    return render(request, 'articles/create.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('article:index')


def detail(request,pk):
    article = Article.objects.get(pk=pk)
    # READ - 특정 게시글에 작성된 모든 댓글 조회 (Article -> Comment 역참조)
    comments = article.comment_set.all()

    # CREATE - 
    comment_form = CommentForm()

    like_count = len(article.like_users.all())
    
    context = {
        'article' : article,
        'comment_form' : comment_form,
        'comments' : comments,
        'like_count' : like_count,
    }    

    return render(request, 'articles/detail.html', context)

@login_required
def update(request, pk):
    # FAQ. 또 commit=False 들고 해야되는 거아닙니까
    # 안달아도됨. 인스턴스에 이미 들어가있음
    # 여기서 instance를 안넣으면 수정이 아니라 생성 과정이 되어버린다.
    # instance에 pk가 담겨 있고, pk는 중복되지 않기 때문에 새로운 데이터로 다시 쓰여진다.
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == "POST": 
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)    
    else :
        return redirect('articles:index')
    
    form = ArticleForm(instance=article)
    
    context = {
        'form' : form,
        'article' : article,
    }
    return render(request, 'articles/update.html', context)

@login_required
def delete(request,pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user :
        article.delete()
    return redirect('articles:index')

@login_required
def create_comments(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = article.comment_set.all()
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        ## commit : SAVE 하는데, DB에 저장하지 않고 인스턴스만 일단 반환해줌
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect('articles:detail', article.pk)
    
    context = {
        'article' : article,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'articles/detail.html', context)

@login_required
def delete_comments(request, article_pk, comment_pk):
    # 어떤 댓글을 삭제할건지 조회
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)


@login_required
def likes(request, article_pk):
    article = Article.objects.get(pk=article_pk)

    # if request.user in article.like_users.all():
    if article.like_users.filter(pk=request.user.pk).exists():
        article.like_users.remove(request.user)
    else :
        article.like_users.add(request.user)
    

    return redirect('articles:detail', article_pk)

web/django_practice/articles/templates/articles/create.html
{% extends "base.html" %}

{% block content %}

<h1>CREATE PAGE</h1>
<!-- method == POST | csrf_token 필요-->
<form action="" method = "POST">
  {% csrf_token %}
  <!--
    ModelForm, Form 만들어주는건 못생겼고
  -->
  {{form}}

  <input type="submit" value="CREATE">
</form>
{% endblock content %}

web/django_practice/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>DETAIL</h1>
  <h2>{{article.pk}} 번째 글 </h2>
  <hr>
  <p> 제목 : {{ article.title }} </p>
  <p> 내용 : {{ article.content }} </p>
  <p> 작성일 : {{ article.created_at }} </p>
  <p> 수정일 : {{ article.updated_at }} </p>
  <p> 작성자 : <a href="{% url "accounts:profile" article.user %}">{{ article.user }} </a></p>
  <p> 좋아요 : {{ like_count }} 개</p>
  <form action="{% url "articles:likes" article.pk %}" method="POST">
    {% csrf_token %}
    {% if request.user in article.like_users.all %}
      <input type="submit" value = "좋아요 취소">
    {% else %}
      <input type="submit" value = "좋아요">
    {% endif %}
  </form>
  {% if request.user == article.user %}
  <form action="{% url "articles:update" article.pk %}" method = "POST">
    {% csrf_token %}
    <input type="submit" value="EDIT">
  </form>
  <form action="{% url "articles:delete" article.pk %}" method = "POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  {% endif %}
  <hr>


  <h3>댓글 작성</h3>
  <form action="{% url "articles:create_comments" article.pk %}" method="POST">
    {% csrf_token %}
    {{comment_form.as_p}}
    <input type="submit" value = "댓글작성">
  </form>
  <h3>댓글 목록</h3>
  <ul>
    {% for comment in comments %}
      <li>
        <p>
          {{comment.user}} : {{comment.content}}
          {% if request.user == comment.user %}
          <form action="{% url "articles:delete_comments" article.pk comment.pk %}" method ="POST" style="display : inline">
            {% csrf_token %}
            <input type="submit" value="댓글 삭제">
          </form>
          {% endif %}
        </p>
      </li>
    {% endfor %}
  </ul>
  <hr>
  <a href="{% url "articles:index" %}">[BACK]</a>
</body>
</html>

web/django_practice/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
<h1>INDEX PAGE</h1>
<hr>
{% if request.user.is_authenticated %}
  <h2>반갑다. {{user}}.</h2>
  <a href="{% url "accounts:profile" user.username%}">
    내 프로필
  </a>
  <form action="{% url "accounts:logout" %}" method="POST">
    {% csrf_token %}
    <input type="submit"value="[LOGOUT]">
  </form>
  <button><a href="{% url "accounts:update" %}">회원정보수정</a></button>
  <form action="{% url "accounts:delete" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="회원탈퇴">
  </form>
  <a href="{% url "articles:create" %}">CREATE</a>
  
{% else %}
  
  <a href="{% url "accounts:login" %}">[LOGIN]</a>
  <button><a href="{% url "accounts:signup" %}">회원가입</a></button>

{% endif %}

  
  
    <form action="{% url "articles:index" %}"> 
      <input type="hidden" name="is_hidden" value="False">
      <input type="submit" value="비공개 글 숨기기">
    </form>
    <form action="{% url "articles:index" %}"> 
      <input type="hidden" name="is_hidden" value="True">
      <input type="submit" value="비공개 글 보이기">
    </form>
  {% for article in articles %}
  <li>
    <a href="{% url "articles:detail" article.pk %}">{{article.pk}}번째 글</a>
    <p>제목 : {{article.title}}</p>
    <p>내용 : {{article.content}}</p>
    <p>작성자 : {{article.user}}</p>
    <p>숨김여부 : {{article.is_hidden}}</p>
    <p>좋아요 : {{article.like_users.all|lengt
      
    }}개</p>
    <hr>
  </li>
  {% endfor %}
</ul>

{% endblock content %}

web/django_practice/articles/templates/articles/update.html
{% extends "base.html" %}

{% block content %}

<h1>UPDATE PAGE</h1>
<!-- method == POST | csrf_token 필요-->
<form action="" method = "POST">
  {% csrf_token %}
  <!--
    ModelForm, Form 만들어주는건 못생겼고
  -->
  {{form}}

  <input type="submit" value="UPDATE">
</form>
{% endblock content %}